KAFKA_BOOTSTRAP = "kafka:9092"

WEATHER_TOPIC = "weather_data_topic"
FLIGHT_TOPIC = "flight_data_topic"
PREDICTION_TOPIC = "prediction_topic"

GROUP_ID = "flink-group"


feature_order = [
    "airline_name",
    "origin_visibility_km",
    "origin_precip_mm",
    "origin_precip_prob_pct",
    "origin_wind_speed_kmph",
    "origin_wind_dir_deg",
    "origin_temp_c",
    "origin_humidity_pct",
    "origin_pressure_mb",
    "origin_cloud_cover_pct",
    "origin_wind_speed_prev1h",
    "origin_wind_speed_3h_mean",
    "origin_precip_3h_sum",
    "origin_visibility_3h_mean",
    "origin_low_visibility_flag",
    "origin_high_wind_flag",
    "origin_high_humidity_flag",
    "origin_rain_intensity",
    "origin_wind_u",
    "origin_wind_v",
    "dest_visibility_km",
    "dest_precip_mm",
    "dest_precip_prob_pct",
    "dest_wind_speed_kmph",
    "dest_wind_dir_deg",
    "dest_temp_c",
    "dest_humidity_pct",
    "dest_pressure_mb",
    "dest_cloud_cover_pct",
    "dest_wind_speed_prev1h",
    "dest_wind_speed_3h_mean",
    "dest_precip_3h_sum",
    "dest_visibility_3h_mean",
    "dest_low_visibility_flag",
    "dest_high_wind_flag",
    "dest_high_humidity_flag",
    "dest_rain_intensity",
    "dest_wind_u",
    "dest_wind_v",
    "route_adj_delay_mean",
    "airline_adj_delay_mean",
    "route_airline_adj_delay_mean",
    "sched_dep_month_enc",
    "sched_dep_dow_enc",
    "sched_dep_time_block_enc",
    "temp_diff",
    "visibility_diff",
    "wind_speed_diff",
    "precip_prob_diff",
    "origin_weather_index",
    "dest_weather_index",
    "route_freq",
    "is_busy_route",
]
